apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kafka-workflow-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka-service:9092"
        - name: TOPIC_NAME
          value: "test-topic"
        - name: GROUP_ID
          value: "test-consumer-group"

